export default {
  extends: ['@commitlint/config-conventional'],
  // Pin commits are machine-generated by khal-release-bot (deploy/gitops-pin.sh)
  // and already live in the eks/** lane history — history rewrite on a gitops
  // lane is off the table, so the linter skips them instead.
  ignores: [(message) => message.startsWith('chore(gitops): pin ')],
};
